# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JWKeyWordFilterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JWKeyWordFilterDemo
  # pod 'JWKeyWordFilter',:git => 'https://github.com/upworldcjw/JWKeyWordFilter.git'

  pod 'JWKeyWordFilter',:path => '..'

end
